### ISSUE TITLE
cap size

### ISSUE THREAD

**Issue by zeeev** [MarcAzar/BitVector#3]
Hi @MarcAzar,

Sorry to bother you again, but I'm not sure the constructor is working properly. Here is my code:

```
 echo "bits requested:", ovls[0].l1
 var aCoverage = newBitVector[uint](ovls[0].l1)
 echo aCoverage
 for i in 0..(ovls[0].l1 - 1):
   echo i, " ", ovls[0].l1 - 1
   aCoverage[i] = 0
```

here is my printed info:
```
bits requested:10278
BitVector with capacity of 10240 bits and 160 unique elements
````

Hitting the assert:
```
Error: unhandled exception: /home/zkronenberg/tools/nim-pb/nimbleDir/pkgs/BitVector-0.4.8/bitvector.nim(67, 9) `i < b.cap and
  0 <= i` Index out of range [AssertionError]
```

**Comment by MarcAzar** [comment]
Hey Zev,
This works fine with the latest version. Please make sure you are using
the latest v0.4.10, you can now initialize with 1s instead of 0s as
well with the latest version.

/Marc
